Add missing lesc parameter to ble_gap_encrypt call (#207)
Fixes clear bug where ble_adapter's encrypt() function is missing
lesc parameter when calling ble_gap_encrypt().

This lead to following error:
TypeError: ble_gap_encrypt() missing 1 required positional argument: 'lesc'

Co-authored-by: Jørn Bøni Hofstad <31501543+jornbh@users.noreply.github.com>