Fix setup.py find_packages usage
* find_packages filter uses fnmatchcase, thus it cannot
  utilize regexp patterns. This caused 'tests' to appear
  in package, which broke dill usage on all projects that
  use pc-ble-driver-py:

  ...
  File "path-to-site-packages/dill/_dill.py", line 474, in find_class
    return StockUnpickler.find_class(self, module, name)
  File "path-to-site-packages/tests/__init__.py", line 4, in <module>
    from driver_setup import Settings
  ModuleNotFoundError: No module named 'driver_setup'